- name: Posts
  entity: socialNetwork.posts.controller
  locationRequired: true
  actions:
    - name: read all
      description: fetch all posts
      slug: socialNetwork.posts.read
      method: read

    - name: read by id
      description: read post by id
      slug: socialNetwork.posts.readById
      method: readById

    - name: create new
      description: create new post
      slug: socialNetwork.posts.create
      method: create

    - name: update by id
      description: update specific post
      slug: socialNetwork.posts.updateById
      method: updateById

    - name: delete by id
      description: delete specific post
      slug: socialNetwork.posts.deleteById
      method: deleteById

    - name: create comment
      description: create new comment to post by id
      slug: socialNetwork.posts.comments.createCommentToId
      method: createCommentToId

    - name: read comments
      description: read comments by post id
      slug: socialNetwork.posts.comments.readCommentsById
      method: readCommentsById